version: '3.8'
services:
  my_mongo:
    image: mongo
    container_name: test_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - '$PWD/mongo:/data/db'
      - '$PWD/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
